[package]
name = "synthia-telemetry"
version.workspace = true
edition.workspace = true

[dependencies]
synthia-core.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
uuid.workspace = true
opentelemetry.workspace = true
opentelemetry_sdk.workspace = true
opentelemetry-semantic-conventions.workspace = true
opentelemetry-otlp.workspace = true
tracing-opentelemetry.workspace = true
tokio.workspace = true
prometheus.workspace = true
lazy_static.workspace = true

[dev-dependencies]
tempfile.workspace = true