/**
 * Plain-JavaScript shadow of `mock-a2a-server.ts`.
 *
 * Re-evaluable via `new Function(...)` inside `page.evaluate`.
 * Kept in lockstep with the `.ts` source — the canonical
 * implementation. Do not edit this file directly; edit the
 * `.ts` file and port the change here.
 *
 * Each SSE event's `data` payload is wrapped in a JSON-RPC
 * 2.0 success envelope (`{jsonrpc, id, result: <data>}`)
 * using the `id` from the request body the SDK POSTs to the
 * mock endpoint. The SDK's `_processSseEventData` parses
 * each frame as JSON, requires `id === originalRequestId`,
 * and reads `result` for the StreamResponse payload — so the
 * mock MUST emit envelopes, not raw `{artifactUpdate: ...}`
 * objects. Tests that need a different envelope shape can
 * pre-encode their events via `buildJsonRpcStreamResponse`
 * (not yet exposed in the `.ts`).
 */

const AGENT_CARD_PATH = '/.well-known/agent-card.json';

function streamToSSEResponse(events) {
  const encoder = new TextEncoder();
  const body = new ReadableStream({
    start(controller) {
      for (const ev of events) {
        if (ev.event) {
          controller.enqueue(encoder.encode(`event: ${ev.event}\n`));
        }
        for (const line of ev.data.split('\n')) {
          controller.enqueue(encoder.encode(`data: ${line}\n`));
        }
        controller.enqueue(encoder.encode('\n'));
      }
      controller.close();
    },
  });
  return new Response(body, {
    status: 200,
    headers: {
      'content-type': 'text/event-stream',
      'cache-control': 'no-cache',
    },
  });
}

function buildAgentCard(fixture) {
  // Default to the page origin so the SDK's transport endpoint
  // is reachable via window.fetch when the test bypasses the
  // mock (e.g. between `_resetClientForTesting` and the next
  // `sendMessageStream`). With the mock in place, the URL is
  // irrelevant — `mockFetch` intercepts every fetch.
  const url =
    (fixture && fixture.url) ||
    (typeof window !== 'undefined' ? window.location.origin + '/a2a' : 'http://localhost/a2a');
  return {
    name: 'Mock Agent',
    description: 'Test fixture for e2e tests',
    version: '1.0',
    url,
    protocolVersion: '1.0',
    supportedInterfaces: [{ protocolBinding: 'JSONRPC', protocolVersion: '1.0', url, tenant: '' }],
    capabilities: { streaming: true, pushNotifications: false },
    defaultInputModes: ['text/plain'],
    defaultOutputModes: ['text/plain'],
    skills: [],
  };
}

function tryParseRequestId(init) {
  if (!init || !init.body) return null;
  const body = typeof init.body === 'string' ? init.body : '';
  if (!body) return null;
  try {
    const parsed = JSON.parse(body);
    if (parsed && typeof parsed.id !== 'undefined') return parsed.id;
  } catch {
    /* ignore */
  }
  return null;
}

function buildMockA2AFetch(config) {
  const agentCardJson = JSON.stringify(buildAgentCard(config.agentCard));
  const userEvents = config.streamEvents;
  return async function (input, init) {
    const url =
      typeof input === 'string' ? input : input instanceof URL ? input.toString() : input.url;
    if (url.endsWith(AGENT_CARD_PATH) || url.includes(AGENT_CARD_PATH)) {
      return new Response(agentCardJson, {
        status: 200,
        headers: { 'content-type': 'application/json' },
      });
    }
    // Wrap each event in a JSON-RPC envelope so the SDK's
    // `_processSseEventData` (which requires `id` and `result`)
    // accepts the frame. Use the request body's `id` if
    // available; fall back to a constant 0 so the test still
    // surfaces events for assertions even when the body is
    // unparseable. After the user's events, append a terminal
    // `statusUpdate` (`TASK_STATE_COMPLETED`) so the chat UI
    // marks the assistant turn as finished — without it the
    // stream stays open and the test's `waitForAssistantReply`
    // times out. Skip the auto-status if the user already
    // supplied one.
    const requestId = tryParseRequestId(init);
    const id = requestId !== null ? requestId : 0;
    const hasTerminal = userEvents.some((ev) => {
      try {
        const parsed = JSON.parse(ev.data);
        return parsed && parsed.statusUpdate && parsed.statusUpdate.status;
      } catch {
        return false;
      }
    });
    const completedPayload = JSON.stringify({
      statusUpdate: {
        taskId: 't',
        contextId: 'c',
        status: { state: 'TASK_STATE_COMPLETED' },
        final: true,
      },
    });
    const allEvents = [...userEvents, ...(hasTerminal ? [] : [{ data: completedPayload }])];
    const wrapped = allEvents.map((ev) => ({
      event: ev.event,
      data: JSON.stringify({ jsonrpc: '2.0', id, result: JSON.parse(ev.data) }),
    }));
    return streamToSSEResponse(wrapped);
  };
}
