//! The [`Error`] enum — the single cross-crate error type for
//! Synthia, used by every workspace member.
//!
//! # Design: thiserror enum + boundary adapter
//!
//! Two-layer split (the axum error-handling pattern):
//!
//! - **Domain layer (this crate)** — [`Error`] owns the failure
//!   taxonomy: one variant per failure mode with pure payload
//!   fields. [`thiserror::Error`] generates `Display` from the
//!   per-variant `#[error("...")]` format strings and
//!   `std::error::Error::source` from the `#[from]` /
//!   `#[source]` payload fields. No hand-written message
//!   methods, no mirror `ErrorKind` classifier: the stable wire
//!   code is [`Error::kind`].
//! - **Transport layer (`synthia-server`)** — the `ApiError`
//!   adapter maps a variant to an HTTP status and a safe JSON
//!   envelope, and logs the full chain (operator-only detail).
//!   See `synthia_server::api::error`.
//!
//! Prefer the helper constructors ([`Error::not_found`],
//! [`Error::validation`], …) over constructing variants
//! directly.

use std::{path::PathBuf, time::Duration};

use thiserror::Error;

/// Top-level Synthia error. Returned by every fallible operation
/// across the workspace.
///
/// - `Display` (generated by thiserror) is the single-line
///   human message; the HTTP layer logs it and copies it into
///   the response envelope's `message` field.
/// - [`Error::kind`] is the stable snake_case wire code for
///   telemetry tags, log fields, and the envelope's `code`
///   field. Renames are breaking and pinned by the
///   `kind_string_table` test.
/// - `std::error::Error::source` routes through the `#[from]` /
///   `#[source]` payload fields (`Io`, `RetryExhausted`) so the
///   original cause stays reachable.
#[derive(Debug, Error)]
#[non_exhaustive]
pub enum Error {
    /// Foreign `std::io::Error`. `#[from]` generates
    /// `From<std::io::Error>` and feeds `source()`.
    #[error("I/O error: {inner}")]
    Io {
        #[from]
        inner: std::io::Error,
    },

    #[error("not found: {item}")]
    NotFound { item: String },

    #[error("already exists: {item}")]
    AlreadyExists { item: String },

    #[error("invalid item: {item}")]
    InvalidItem { item: String },

    #[error("parse error: {message}")]
    Parse { message: String },

    #[error("internal error: {message}")]
    Internal { message: String },

    #[error("unauthorized: {message}")]
    Unauthorized { message: String },

    #[error("forbidden: {message}")]
    Forbidden { message: String },

    #[error("validation error: {message}")]
    Validation { message: String },

    #[error("tool execution error: {message}")]
    ToolExecution { message: String },

    #[error("provider error: {message}")]
    Provider { message: String },

    #[error("session error: {message}")]
    Session { message: String },

    #[error("skill error: {message}")]
    Skill { message: String },

    #[error("memory error: {message}")]
    Memory { message: String },

    #[error("guardian violation: {message}")]
    GuardianViolation { message: String },

    #[error(
        "edit conflict on {}: original_hash={}, current_hash={}",
        .path.display(),
        .original_hash,
        .current_hash
    )]
    EditConflict {
        path: PathBuf,
        original_hash: u64,
        current_hash: u64,
    },

    #[error("rate limited, retry after {retry_after:?}")]
    RateLimited { retry_after: Option<Duration> },

    #[error("request failed with status {status}: {message}")]
    RequestFailed { status: u16, message: String },

    #[error("stream error: {message}")]
    Stream { message: String },

    #[error("stream error: (http_failure): {message}")]
    StreamHttpFailure { message: String },

    #[error("stream error: (protocol_error): {message}")]
    StreamProtocolError { message: String },

    #[error("stream error: (aborted): {message}")]
    StreamAborted { message: String },

    #[error("stream error: (internal): {message}")]
    StreamInternal { message: String },

    #[error("timeout: {message}")]
    Timeout { message: String },

    #[error("retry exhausted after {attempts} attempts: {last_error}")]
    RetryExhausted {
        attempts: u32,
        #[source]
        last_error: Box<Error>,
    },

    #[error("model not found: {message}")]
    ModelNotFound { message: String },

    #[error("model unavailable: {message}")]
    ModelUnavailable { message: String },

    #[error("config error: {message}")]
    Config { message: String },

    #[error("model router error: {message}")]
    Router { message: String },

    #[error("context error: {message}")]
    Context { message: String },

    #[error("telemetry error: {message}")]
    Telemetry { message: String },

    #[error("multiagent error: {message}")]
    Multiagent { message: String },

    #[error("evaluation error: {message}")]
    Evaluation { message: String },

    #[error(
        "context overflow: {actual_tokens} tokens used, limit is {limit_tokens}"
    )]
    ContextOverflow {
        limit_tokens: u64,
        actual_tokens: u64,
    },

    #[error(
        "doom loop detected on '{tool_name}' after {iterations} iterations"
    )]
    DoomLoop { tool_name: String, iterations: u32 },

    #[error("prompt injection detected in {input_source}: pattern '{pattern}'")]
    PromptInjection {
        input_source: String,
        pattern: String,
    },
}

impl Error {
    // -----------------------------------------------------------------
    // Helper constructors.
    //
    // Kept constructors are those actually used by workspace
    // production code (grep-verified). Other variants still exist
    // on the enum to keep the wire-code table stable; their
    // payloads can be constructed directly when needed.
    // -----------------------------------------------------------------

    /// Construct an [`Error::NotFound`].
    pub fn not_found(item: impl Into<String>) -> Self {
        Self::NotFound { item: item.into() }
    }

    /// Construct an [`Error::AlreadyExists`].
    pub fn already_exists(item: impl Into<String>) -> Self {
        Self::AlreadyExists { item: item.into() }
    }

    /// Construct an [`Error::InvalidItem`].
    pub fn invalid_item(item: impl Into<String>) -> Self {
        Self::InvalidItem { item: item.into() }
    }

    /// Construct an [`Error::Parse`].
    pub fn parse(message: impl Into<String>) -> Self {
        Self::Parse {
            message: message.into(),
        }
    }

    /// Construct an [`Error::Internal`].
    pub fn internal(message: impl Into<String>) -> Self {
        Self::Internal {
            message: message.into(),
        }
    }

    /// Construct an [`Error::Validation`].
    pub fn validation(message: impl Into<String>) -> Self {
        Self::Validation {
            message: message.into(),
        }
    }

    /// Construct an [`Error::Provider`].
    pub fn provider(message: impl Into<String>) -> Self {
        Self::Provider {
            message: message.into(),
        }
    }

    /// Construct an [`Error::Session`].
    pub fn session(message: impl Into<String>) -> Self {
        Self::Session {
            message: message.into(),
        }
    }

    /// Construct an [`Error::Forbidden`].
    pub fn forbidden(message: impl Into<String>) -> Self {
        Self::Forbidden {
            message: message.into(),
        }
    }

    /// Construct an [`Error::Timeout`].
    pub fn timeout(message: impl Into<String>) -> Self {
        Self::Timeout {
            message: message.into(),
        }
    }

    /// Construct an [`Error::Config`].
    pub fn config(message: impl Into<String>) -> Self {
        Self::Config {
            message: message.into(),
        }
    }

    /// Construct an [`Error::Telemetry`].
    pub fn telemetry(message: impl Into<String>) -> Self {
        Self::Telemetry {
            message: message.into(),
        }
    }

    /// Construct an [`Error::Stream`].
    pub fn stream(message: impl Into<String>) -> Self {
        Self::Stream {
            message: message.into(),
        }
    }

    /// Construct an [`Error::RateLimited`].
    pub fn rate_limited(retry_after: Option<Duration>) -> Self {
        Self::RateLimited { retry_after }
    }

    /// Construct an [`Error::RequestFailed`].
    pub fn request_failed(status: u16, message: impl Into<String>) -> Self {
        Self::RequestFailed {
            status,
            message: message.into(),
        }
    }

    /// Construct an [`Error::EditConflict`].
    pub fn edit_conflict(
        path: impl Into<PathBuf>,
        original_hash: u64,
        current_hash: u64,
    ) -> Self {
        Self::EditConflict {
            path: path.into(),
            original_hash,
            current_hash,
        }
    }

    /// Construct an [`Error::ContextOverflow`].
    pub fn context_overflow(limit_tokens: u64, actual_tokens: u64) -> Self {
        Self::ContextOverflow {
            limit_tokens,
            actual_tokens,
        }
    }

    /// Construct an [`Error::DoomLoop`].
    pub fn doom_loop(tool_name: impl Into<String>, iterations: u32) -> Self {
        Self::DoomLoop {
            tool_name: tool_name.into(),
            iterations,
        }
    }

    /// Construct an [`Error::PromptInjection`].
    pub fn prompt_injection(
        source: impl Into<String>,
        pattern: impl Into<String>,
    ) -> Self {
        Self::PromptInjection {
            input_source: source.into(),
            pattern: pattern.into(),
        }
    }

    /// Construct an [`Error::RetryExhausted`].
    pub fn retry_exhausted(attempts: u32, last_error: Error) -> Self {
        Self::RetryExhausted {
            attempts,
            last_error: Box::new(last_error),
        }
    }

    /// Construct an [`Error::StreamHttpFailure`] (upstream
    /// HTTP transport failure — connection, TLS, status).
    pub fn stream_http_failure(message: impl Into<String>) -> Self {
        Self::StreamHttpFailure {
            message: message.into(),
        }
    }

    /// Construct an [`Error::StreamAborted`] (caller cancelled
    /// the stream).
    pub fn stream_aborted(message: impl Into<String>) -> Self {
        Self::StreamAborted {
            message: message.into(),
        }
    }

    // -----------------------------------------------------------------
    // Classification
    // -----------------------------------------------------------------

    /// Returns true if this error is retryable based on its type
    /// or status code.
    pub fn is_retryable(&self) -> bool {
        match self {
            Self::RequestFailed { status, .. } => {
                matches!(status, 429 | 500 | 502 | 503 | 504)
            }
            Self::Stream { .. }
            | Self::StreamHttpFailure { .. }
            | Self::StreamProtocolError { .. }
            | Self::StreamInternal { .. } => true,
            Self::Timeout { .. } => true,
            Self::RateLimited { .. } => true,
            _ => false,
        }
    }

    /// Returns true if this error indicates rate limiting.
    pub fn is_rate_limited(&self) -> bool {
        matches!(self, Self::RateLimited { .. })
    }

    // -----------------------------------------------------------------
    // Wire code
    //
    // The canonical snake_case wire code is owned by the server
    // boundary (`From<synthia_core::Error> for AppError` in
    // `synthia-server`), which inlines `(status, code)` per
    // variant. Core is intentionally dumb: it owns the variant
    // taxonomy, the Display strings, and the source-chain
    // routing; everything transport-specific lives one layer
    // up.
    // -----------------------------------------------------------------
}

// -----------------------------------------------------------------------------
// From impls for foreign error types.
//
// `From<std::io::Error>` is generated by thiserror's `#[from]` on
// the `Io` variant.
// -----------------------------------------------------------------------------

impl From<reqwest::Error> for Error {
    fn from(e: reqwest::Error) -> Self {
        // Classify via the reqwest API surface
        // (`is_timeout` / `is_connect` / …) so callers keep the
        // transport-specific semantics.
        let msg = e.to_string();
        if e.is_timeout() {
            Self::Timeout { message: msg }
        } else if e.is_connect() {
            Self::Stream { message: msg }
        } else if e.is_request() && e.is_redirect() {
            Self::RequestFailed {
                status: 0,
                message: msg,
            }
        } else {
            Self::Internal { message: msg }
        }
    }
}

impl From<serde_json::Error> for Error {
    fn from(e: serde_json::Error) -> Self {
        Self::Parse {
            message: e.to_string(),
        }
    }
}

impl From<serde_yaml::Error> for Error {
    fn from(e: serde_yaml::Error) -> Self {
        Self::Parse {
            message: format!("yaml error: {e}"),
        }
    }
}

#[cfg(test)]
mod tests {

    use super::*;

    // -- Display (thiserror-generated) -------------------------------

    /// Every variant's Display format is pinned verbatim — the
    /// HTTP layer copies Display into the response envelope's
    /// `message` field, so wording changes are wire-visible.
    #[test]
    fn display_formats_are_pinned() {
        let io: Error = std::io::Error::other("disk full").into();
        assert_eq!(io.to_string(), "I/O error: disk full");
        assert_eq!(Error::not_found("widget").to_string(), "not found: widget");
        assert_eq!(
            Error::already_exists("skill 'x'").to_string(),
            "already exists: skill 'x'"
        );
        assert_eq!(
            Error::invalid_item("bad label").to_string(),
            "invalid item: bad label"
        );
        assert_eq!(
            Error::validation("bad").to_string(),
            "validation error: bad"
        );
        assert_eq!(Error::internal("boom").to_string(), "internal error: boom");
        assert_eq!(
            Error::rate_limited(None).to_string(),
            "rate limited, retry after None"
        );
        assert_eq!(
            Error::edit_conflict("/tmp/f", 1, 2).to_string(),
            "edit conflict on /tmp/f: original_hash=1, current_hash=2"
        );
        assert_eq!(
            Error::context_overflow(100, 200).to_string(),
            "context overflow: 200 tokens used, limit is 100"
        );
        assert_eq!(
            Error::doom_loop("bash", 5).to_string(),
            "doom loop detected on 'bash' after 5 iterations"
        );
        assert_eq!(
            Error::prompt_injection("user_input", "ignore previous")
                .to_string(),
            "prompt injection detected in user_input: pattern \
             'ignore previous'"
        );
        assert_eq!(
            Error::StreamInternal {
                message: "x".into()
            }
            .to_string(),
            "stream error: (internal): x"
        );
        assert_eq!(
            Error::StreamHttpFailure {
                message: "x".into()
            }
            .to_string(),
            "stream error: (http_failure): x"
        );
        assert_eq!(
            Error::StreamAborted {
                message: "x".into()
            }
            .to_string(),
            "stream error: (aborted): x"
        );
        assert_eq!(
            Error::retry_exhausted(3, Error::timeout("upstream")).to_string(),
            "retry exhausted after 3 attempts: timeout: upstream"
        );
    }

    // -- helper constructors ------------------------------------------

    /// Each helper constructor MUST produce its specific variant
    /// (not a sibling variant with the same fields).
    #[test]
    fn helpers_produce_distinct_variants() {
        use Error as E;
        assert!(matches!(E::not_found("x"), E::NotFound { .. }));
        assert!(matches!(E::already_exists("x"), E::AlreadyExists { .. }));
        assert!(matches!(E::invalid_item("x"), E::InvalidItem { .. }));
        assert!(matches!(E::validation("x"), E::Validation { .. }));
        assert!(matches!(E::internal("x"), E::Internal { .. }));
        assert!(matches!(
            Error::Unauthorized {
                message: "x".into()
            },
            Error::Unauthorized { .. }
        ));
        assert!(matches!(Error::forbidden("x"), Error::Forbidden { .. }));
        assert!(matches!(Error::parse("x"), Error::Parse { .. }));
        assert!(matches!(
            Error::ToolExecution {
                message: "x".into()
            },
            Error::ToolExecution { .. }
        ));
        assert!(matches!(Error::provider("x"), Error::Provider { .. }));
        assert!(matches!(Error::session("x"), Error::Session { .. }));
        assert!(matches!(
            Error::Skill {
                message: "x".into()
            },
            Error::Skill { .. }
        ));
        assert!(matches!(
            Error::Memory {
                message: "x".into()
            },
            Error::Memory { .. }
        ));
        assert!(matches!(
            Error::GuardianViolation {
                message: "x".into()
            },
            Error::GuardianViolation { .. }
        ));
        assert!(matches!(Error::stream("x"), Error::Stream { .. }));
        assert!(matches!(Error::timeout("x"), Error::Timeout { .. }));
        assert!(matches!(
            Error::ModelNotFound {
                message: "x".into()
            },
            Error::ModelNotFound { .. }
        ));
        assert!(matches!(
            Error::ModelUnavailable {
                message: "x".into()
            },
            Error::ModelUnavailable { .. }
        ));
        assert!(matches!(Error::config("x"), Error::Config { .. }));
        assert!(matches!(
            Error::Router {
                message: "x".into()
            },
            Error::Router { .. }
        ));
        assert!(matches!(
            Error::Context {
                message: "x".into()
            },
            Error::Context { .. }
        ));
        assert!(matches!(Error::telemetry("x"), Error::Telemetry { .. }));
        assert!(matches!(
            Error::Multiagent {
                message: "x".into()
            },
            Error::Multiagent { .. }
        ));
        assert!(matches!(
            Error::Evaluation {
                message: "x".into()
            },
            Error::Evaluation { .. }
        ));
        assert!(matches!(
            E::context_overflow(1, 2),
            E::ContextOverflow { .. }
        ));
        assert!(matches!(E::doom_loop("t", 1), E::DoomLoop { .. }));
        assert!(matches!(
            E::prompt_injection("s", "p"),
            E::PromptInjection { .. }
        ));
        assert!(matches!(
            Error::StreamInternal {
                message: "x".into()
            },
            Error::StreamInternal { .. }
        ));
        assert!(matches!(
            Error::StreamHttpFailure {
                message: "x".into()
            },
            Error::StreamHttpFailure { .. }
        ));
        assert!(matches!(
            Error::StreamAborted {
                message: "x".into()
            },
            Error::StreamAborted { .. }
        ));
        assert!(matches!(
            Error::StreamProtocolError {
                message: "x".into()
            },
            Error::StreamProtocolError { .. }
        ));
        assert!(matches!(E::rate_limited(None), E::RateLimited { .. }));
        assert!(matches!(
            E::request_failed(500, "x"),
            E::RequestFailed { .. }
        ));
        assert!(matches!(
            E::edit_conflict("p", 0, 0),
            E::EditConflict { .. }
        ));
        assert!(matches!(
            E::retry_exhausted(1, E::internal("x")),
            E::RetryExhausted { .. }
        ));
        assert!(matches!(std::io::Error::other("x"), std::io::Error { .. }));
    }

    // -- payload round-trips ------------------------------------------

    #[test]
    fn rate_limited_constructor_stores_retry_after() {
        let e = Error::rate_limited(Some(Duration::from_secs(7)));
        assert!(e.is_rate_limited());
        let Error::RateLimited { retry_after, .. } = e else {
            panic!("expected RateLimited variant");
        };
        assert_eq!(retry_after, Some(Duration::from_secs(7)));

        let Error::RateLimited { retry_after, .. } = Error::rate_limited(None)
        else {
            panic!("expected RateLimited variant");
        };
        assert_eq!(retry_after, None);
    }

    #[test]
    fn request_failed_constructor_stores_status_and_message() {
        let Error::RequestFailed {
            status, message, ..
        } = Error::request_failed(503, "service unavailable")
        else {
            panic!("expected RequestFailed variant");
        };
        assert_eq!(status, 503);
        assert_eq!(message, "service unavailable");
    }

    #[test]
    fn edit_conflict_constructor_stores_path_and_hashes() {
        let path = PathBuf::from("/etc/config.toml");
        let Error::EditConflict {
            path: p,
            original_hash,
            current_hash,
        } = Error::edit_conflict(path.clone(), 0xDEAD_BEEF, 0xCAFE_BABE)
        else {
            panic!("expected EditConflict variant");
        };
        assert_eq!(p, path);
        assert_eq!(original_hash, 0xDEAD_BEEF);
        assert_eq!(current_hash, 0xCAFE_BABE);
    }

    #[test]
    fn context_overflow_constructor_stores_token_counts() {
        let Error::ContextOverflow {
            limit_tokens,
            actual_tokens,
            ..
        } = Error::context_overflow(100_000, 150_000)
        else {
            panic!("expected ContextOverflow variant");
        };
        assert_eq!(limit_tokens, 100_000);
        assert_eq!(actual_tokens, 150_000);
    }

    #[test]
    fn doom_loop_constructor_stores_tool_and_iterations() {
        let Error::DoomLoop {
            tool_name,
            iterations,
            ..
        } = Error::doom_loop("bash", 42)
        else {
            panic!("expected DoomLoop variant");
        };
        assert_eq!(tool_name, "bash");
        assert_eq!(iterations, 42);
    }

    #[test]
    fn prompt_injection_constructor_stores_source_and_pattern() {
        let Error::PromptInjection {
            input_source,
            pattern,
            ..
        } = Error::prompt_injection("user_input", "ignore previous")
        else {
            panic!("expected PromptInjection variant");
        };
        assert_eq!(input_source, "user_input");
        assert_eq!(pattern, "ignore previous");
    }

    #[test]
    fn retry_exhausted_constructor_stores_attempts_and_inner_error() {
        let inner = Error::timeout("upstream");
        let Error::RetryExhausted { attempts, .. } =
            Error::retry_exhausted(3, inner)
        else {
            panic!("expected RetryExhausted variant");
        };
        assert_eq!(attempts, 3);
    }

    // -- retryability --------------------------------------------------

    #[test]
    fn retryability_classification() {
        assert!(Error::request_failed(429, "x").is_retryable());
        assert!(Error::request_failed(500, "x").is_retryable());
        assert!(Error::request_failed(503, "x").is_retryable());
        assert!(!Error::request_failed(400, "x").is_retryable());
        assert!(!Error::request_failed(401, "x").is_retryable());
        assert!(Error::stream("x").is_retryable());
        assert!(Error::stream_http_failure("x").is_retryable());
        assert!(
            Error::StreamProtocolError {
                message: "x".into()
            }
            .is_retryable()
        );
        assert!(
            Error::StreamInternal {
                message: "x".into()
            }
            .is_retryable()
        );
        assert!(!Error::stream_aborted("x").is_retryable());
        assert!(!Error::provider("x").is_retryable());
        assert!(!Error::validation("x").is_retryable());
        assert!(!Error::internal("x").is_retryable());
    }

    // -- source chain ---------------------------------------------------

    /// `source()` MUST route through the `#[from]` / `#[source]`
    /// payload fields so the original cause stays reachable
    /// (the attachment-style `source` chain for logging).
    #[test]
    fn source_routes_through_payload_fields() {
        use std::error::Error as _;

        let io: Error = std::io::Error::other("inner").into();
        assert_eq!(
            io.source().map(|s| s.to_string()),
            Some("inner".to_string())
        );

        let e = Error::retry_exhausted(2, Error::timeout("upstream"));
        assert_eq!(
            e.source().map(|s| s.to_string()),
            Some("timeout: upstream".to_string())
        );

        assert!(Error::not_found("x").source().is_none());
    }

    // -- From impls ------------------------------------------------------

    #[test]
    fn from_io_error_produces_io_variant() {
        let io_err = std::io::Error::new(
            std::io::ErrorKind::PermissionDenied,
            "no access",
        );
        let Error::Io { inner, .. } = io_err.into() else {
            panic!("expected Io variant from io::Error");
        };
        assert_eq!(inner.kind(), std::io::ErrorKind::PermissionDenied);
    }

    #[test]
    fn io_variant_only_via_from_io() {
        let e: Error = std::io::Error::other("x").into();
        assert!(matches!(e, Error::Io { .. }));
    }

    #[test]
    fn from_serde_json_error_produces_parse_variant() {
        let json_err: serde_json::Error =
            serde_json::from_str::<serde_json::Value>("{bad").unwrap_err();
        let Error::Parse { message, .. } = json_err.into() else {
            panic!("expected Parse variant from JSON error");
        };
        assert!(!message.is_empty(), "message must be populated");
    }

    #[test]
    fn from_serde_yaml_error_produces_parse_variant_with_prefix() {
        let yaml_err: serde_yaml::Error =
            serde_yaml::from_str::<serde_yaml::Value>("k: : :").unwrap_err();
        let Error::Parse { message, .. } = yaml_err.into() else {
            panic!("expected Parse variant from YAML error");
        };
        assert!(
            message.starts_with("yaml error: "),
            "yaml prefix required (got {message:?})"
        );
    }
}
