//! Cursor pagination utilities for V2 list endpoints.

use base64::{Engine as _, engine::general_purpose::URL_SAFE_NO_PAD};
use serde::{Deserialize, Serialize, de::DeserializeOwned};

use crate::api::error::ApiError;

/// Pagination direction.
#[derive(
    Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize,
)]
pub enum Direction {
    #[default]
    Forward,
    Backward,
}

/// Opaque cursor wrapping an inner value.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Cursor<T>(pub T);

impl<T: Serialize> Cursor<T> {
    /// Encode the cursor as a URL-safe, unpadded base64 JSON blob.
    pub fn encode(&self) -> String {
        let json = serde_json::to_string(&self.0)
            .expect("cursor value should always be serializable");
        URL_SAFE_NO_PAD.encode(json.as_bytes())
    }
}

impl<T: DeserializeOwned> Cursor<T> {
    /// Decode a cursor from a URL-safe, unpadded base64 JSON blob.
    pub fn decode(s: &str) -> Result<Self, ApiError> {
        let bytes = URL_SAFE_NO_PAD
            .decode(s.as_bytes())
            .map_err(|_| ApiError::invalid_cursor())?;
        let inner = serde_json::from_slice(&bytes)
            .map_err(|_| ApiError::invalid_cursor())?;
        Ok(Cursor(inner))
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct PaginatedResponse<T> {
    pub data: Vec<T>,
    pub meta: PaginationMeta,
    pub links: PaginationLinks,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct PaginationMeta {
    pub has_next: bool,
    pub next_cursor: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct PaginationLinks {
    pub self_link: String,
    pub next: Option<String>,
}

/// Build a paginated response from a slice of items.
///
/// `items` should contain up to `limit + 1` items so the helper can detect a
/// next page. If a next page exists, the `next_cursor` is generated by
/// applying `encode_fn` to the caller-supplied cursor value.
pub fn paginate_with_cursor<T, C, F>(
    mut items: Vec<T>,
    cursor: Option<C>,
    limit: usize,
    direction: Direction,
    base_url: &str,
    encode_fn: F,
) -> PaginatedResponse<T>
where
    F: Fn(&C) -> String,
{
    let has_next = items.len() > limit;
    if has_next {
        items.truncate(limit);
    }

    let next_cursor = if has_next {
        cursor.as_ref().map(encode_fn)
    } else {
        None
    };

    let next_link = next_cursor.as_ref().map(|c| {
        let direction_param = match direction {
            Direction::Forward => "",
            Direction::Backward => "&direction=backward",
        };
        format!("{}?cursor={}{}", base_url, c, direction_param)
    });

    PaginatedResponse {
        data: items,
        meta: PaginationMeta {
            has_next,
            next_cursor,
        },
        links: PaginationLinks {
            self_link: base_url.to_string(),
            next: next_link,
        },
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
    struct SessionCursor {
        updated_at: String,
        id: String,
    }

    #[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
    struct MessageCursor {
        seq: u64,
    }

    #[test]
    fn session_cursor_round_trip() {
        let original = Cursor(SessionCursor {
            updated_at: "2026-06-21T10:00:00Z".to_string(),
            id: "sess_123".to_string(),
        });
        let encoded = original.encode();
        let decoded = Cursor::<SessionCursor>::decode(&encoded).unwrap();
        assert_eq!(original, decoded);
    }

    #[test]
    fn message_cursor_round_trip() {
        let original = Cursor(MessageCursor { seq: 42 });
        let encoded = original.encode();
        let decoded = Cursor::<MessageCursor>::decode(&encoded).unwrap();
        assert_eq!(original, decoded);
    }

    #[test]
    fn decode_invalid_base64_returns_invalid_cursor() {
        let err = Cursor::<MessageCursor>::decode("not-base64!!!").unwrap_err();
        assert_eq!(err.code, "invalid_cursor");
    }

    #[test]
    fn decode_invalid_json_returns_invalid_cursor() {
        // Valid base64, but the JSON does not match MessageCursor.
        let encoded = URL_SAFE_NO_PAD.encode(b"\"not-an-object\"");
        let err = Cursor::<MessageCursor>::decode(&encoded).unwrap_err();
        assert_eq!(err.code, "invalid_cursor");
    }

    #[test]
    fn paginate_without_extra_items_has_no_next() {
        let items = vec!["a", "b", "c"];
        let response = paginate_with_cursor(
            items,
            Some("cursor_value"),
            5,
            Direction::Forward,
            "/api/v2/sessions",
            |c| c.to_string(),
        );
        assert_eq!(response.data.len(), 3);
        assert!(!response.meta.has_next);
        assert!(response.meta.next_cursor.is_none());
        assert!(response.links.next.is_none());
    }

    #[test]
    fn paginate_with_extra_item_truncates_and_provides_next_cursor() {
        let items = vec!["a", "b", "c", "d"];
        let response = paginate_with_cursor(
            items,
            Some("next_cursor"),
            3,
            Direction::Forward,
            "/api/v2/sessions",
            |c| c.to_string(),
        );
        assert_eq!(response.data.len(), 3);
        assert!(response.meta.has_next);
        assert_eq!(response.meta.next_cursor, Some("next_cursor".to_string()));
        assert_eq!(
            response.links.next,
            Some("/api/v2/sessions?cursor=next_cursor".to_string())
        );
    }

    #[test]
    fn paginate_backward_includes_direction_in_next_link() {
        let items = vec!["a", "b", "c", "d"];
        let response = paginate_with_cursor(
            items,
            Some("prev_cursor"),
            3,
            Direction::Backward,
            "/api/v2/sessions",
            |c| c.to_string(),
        );
        assert!(response.meta.has_next);
        assert_eq!(
            response.links.next,
            Some(
                "/api/v2/sessions?cursor=prev_cursor&direction=backward"
                    .to_string()
            )
        );
    }
}
