[package]
name = "synthia-evaluation"
version.workspace = true
edition.workspace = true

[dependencies]
async-trait.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
indexmap.workspace = true
parking_lot.workspace = true
synthia-core = { path = "../synthia-core" }
tokio.workspace = true
