[package]
name = "synthia-service"
version.workspace = true
edition.workspace = true

[dependencies]
synthia-core = { path = "../synthia-core" }
async-trait.workspace = true
dashmap.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tracing.workspace = true
tokio.workspace = true
tokio-util.workspace = true
parking_lot.workspace = true

[features]
default = []
